### ISSUE TITLE
`unknown key 'a' at path: $[0]` - Crashes "tasks"  &  fails to export data

### ISSUE THREAD

**Issue by GiorgosXou** [mhss1/MyBrain#214]
**Describe the bug**
The app crashes every time I open "tasks" and fails to export data due to *(I suspect)* an `unknown key 'a' at path: $[0]`  *(I think this started happening since the latest version)*

**To Reproduce**
1. Idk you might try adding a task with this name `🔋 φορτιστής ` *(greek or an emoji?)*

**Expected behavior**
It shouldn't crash :P

**Smartphone:**
 - Device: [Xiaomi Redmi 5A](https://www.gsmarena.com/xiaomi_redmi_5a-8898.php) <sup><sub>*([debloated](https://github.com/GiorgosXou/Our-Xiaomi-Redmi-5A-riva-debloating-list/blob/main/devices/Xiaomi%20Redmi%205A%20riva.txt))*</sub></sup>
 - OS: Android 8.1.0
 - App Version: 1.0.7

**Additional context**
Here's the ``` adb logcat --pid=`adb shell pidof -s com.mhss.app.mybrain` ```  when opening "tasks":
```
--------- beginning of main
07-20 05:29:40.027 13127 13127 W zygote64: miui_dex2oat:　OatFile: /data/app/com.mhss.app.mybrain-jDwcYYB9llKEEA3JLHU1wg==/oat/arm64/base.odex Compiler-Filter = speed-profile
07-20 05:29:40.063 13127 13127 W ResourceType: No package identifier when getting name for resource number 0x00000000
07-20 05:29:40.079 13127 13127 W ResourceType: No package identifier when getting name for resource number 0x00000000
07-20 05:29:40.086 13127 13127 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
07-20 05:29:40.087 13127 13127 W ResourceType: No package identifier when getting name for resource number 0x00000000
07-20 05:29:40.109 13127 13127 D AccessibilityManager: AccessibilityManager status: mPackageName = com.mhss.app.mybrain, mOptimizeEnabled = false, mIsEnabled = false, mIsUiAutomationEnabled = false, mIsInterestedPackage =false
07-20 05:29:40.157 13127 13146 D OpenGLRenderer: HWUI GL Pipeline
07-20 05:29:40.410 13127 13146 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/04/18, d916c72, I7663a5f222
07-20 05:29:40.413 13127 13146 D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
07-20 05:29:40.419 13127 13127 D Compose Focus: Owner FocusChanged(true)
07-20 05:29:40.419 13127 13146 I zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
07-20 05:29:40.420 13127 13146 I OpenGLRenderer: Initialized EGL, version 1.4
07-20 05:29:40.420 13127 13146 D OpenGLRenderer: Swap behavior 2
07-20 05:29:40.429 13127 13146 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
07-20 05:29:40.432 13127 13146 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
07-20 05:29:40.433 13127 13146 D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
07-20 05:29:40.508 13127 13146 D vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
07-20 05:29:40.509 13127 13146 D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
--------- beginning of crash
07-20 05:30:15.798 13127 13127 E AndroidRuntime: FATAL EXCEPTION: main
07-20 05:30:15.798 13127 13127 E AndroidRuntime: Process: com.mhss.app.mybrain, PID: 13127
07-20 05:30:15.798 13127 13127 E AndroidRuntime: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 3: Encountered an unknown key 'a' at path: $[0]
07-20 05:30:15.798 13127 13127 E AndroidRuntime: Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
07-20 05:30:15.798 13127 13127 E AndroidRuntime: JSON input: [{"a":"🔋 φορτιστής ","b":true,"c.....
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at kotlinx.serialization.json.internal.WriteModeKt.JsonDecodingException(SourceFile:1)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at kotlinx.serialization.json.internal.WriteModeKt.JsonDecodingException(SourceFile:2)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(Unknown Source:58)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(Unknown Source:526)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at com.mhss.app.mybrain.domain.model.SubTask$$serializer.deserialize(Unknown Source:20)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(Unknown Source:5)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at kotlin.text.UStringsKt.decodeSerializableElement(Unknown Source:10)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(Unknown Source:49)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(Unknown Source:7)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at kotlinx.serialization.internal.CollectionLikeSerializer.merge(Unknown Source:34)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at kotlinx.serialization.internal.CollectionLikeSerializer.deserialize(Unknown Source:5)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(Unknown Source:5)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at kotlinx.serialization.json.Json.decodeFromString(Unknown Source:30)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at okio.Path$Companion.toSubTasksList(Unknown Source:21)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at com.mhss.app.mybrain.data.local.dao.TaskDao_Impl$11.call(Unknown Source:531)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(Unknown Source:80)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:112)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-20 05:30:15.798 13127 13127 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
--------- beginning of system
07-20 05:30:15.801 13127 13127 E MQSEventManagerDelegate: failed to get MQSService.
07-20 05:30:15.845 13127 13127 I Process : Sending signal. PID: 13127 SIG: 9
```

... and here's when exporting data:
```
--------- beginning of main
07-20 05:32:49.131 13290 13290 W zygote64: miui_dex2oat:　OatFile: /data/app/com.mhss.app.mybrain-jDwcYYB9llKEEA3JLHU1wg==/oat/arm64/base.odex Compiler-Filter = speed-profile
07-20 05:32:49.151 13290 13290 I zygote64: Waiting for a blocking GC AddRemoveAppImageSpace
07-20 05:32:49.159 13290 13290 I zygote64: WaitForGcToComplete blocked AddRemoveAppImageSpace on HeapTrim for 7.764ms
07-20 05:32:49.176 13290 13290 W ResourceType: No package identifier when getting name for resource number 0x00000000
07-20 05:32:49.194 13290 13290 W ResourceType: No package identifier when getting name for resource number 0x00000000
07-20 05:32:49.201 13290 13290 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
07-20 05:32:49.201 13290 13290 W ResourceType: No package identifier when getting name for resource number 0x00000000
07-20 05:32:49.217 13290 13290 D AccessibilityManager: AccessibilityManager status: mPackageName = com.mhss.app.mybrain, mOptimizeEnabled = false, mIsEnabled = false, mIsUiAutomationEnabled = false, mIsInterestedPackage =false
07-20 05:32:49.254 13290 13310 D OpenGLRenderer: HWUI GL Pipeline
07-20 05:32:49.505 13290 13310 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/04/18, d916c72, I7663a5f222
07-20 05:32:49.508 13290 13310 D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
07-20 05:32:49.513 13290 13310 I zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
07-20 05:32:49.513 13290 13310 I OpenGLRenderer: Initialized EGL, version 1.4
07-20 05:32:49.513 13290 13310 D OpenGLRenderer: Swap behavior 2
07-20 05:32:49.515 13290 13290 D Compose Focus: Owner FocusChanged(true)
07-20 05:32:49.519 13290 13310 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
07-20 05:32:49.522 13290 13310 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
07-20 05:32:49.524 13290 13310 D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
07-20 05:32:49.599 13290 13310 D vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
07-20 05:32:49.600 13290 13310 D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
07-20 05:33:03.556 13290 13294 I zygote64: Do partial code cache collection, code=29KB, data=30KB
07-20 05:33:03.557 13290 13294 I zygote64: After code cache collection, code=29KB, data=30KB
07-20 05:33:03.557 13290 13294 I zygote64: Increasing code cache capacity to 128KB
07-20 05:33:03.852 13290 13310 W Adreno-ES20: <core_glFinish:34>: glFinish skipped: 0
07-20 05:33:03.859 13290 13310 W Adreno-ES20: <core_glFinish:34>: glFinish skipped: 0
07-20 05:33:03.884 13290 13310 W Adreno-ES20: <core_glFinish:34>: glFinish skipped: 0
07-20 05:33:03.890 13290 13310 I chatty  : uid=10149(com.mhss.app.mybrain) RenderThread identical 2 lines
07-20 05:33:03.895 13290 13310 W Adreno-ES20: <core_glFinish:34>: glFinish skipped: 0
07-20 05:33:26.380 13290 13310 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/04/18, d916c72, I7663a5f222
07-20 05:33:26.380 13290 13310 I zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
07-20 05:33:26.380 13290 13310 I OpenGLRenderer: Initialized EGL, version 1.4
07-20 05:33:26.380 13290 13310 D OpenGLRenderer: Swap behavior 2
07-20 05:33:26.388 13290 13310 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
07-20 05:33:26.391 13290 13310 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
07-20 05:33:26.392 13290 13310 D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
07-20 05:33:26.545 13290 13325 W System.err: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 3: Encountered an unknown key 'a' at path: $[0]
07-20 05:33:26.545 13290 13325 W System.err: Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
07-20 05:33:26.545 13290 13325 W System.err: JSON input: [{"a":"🔋 φορτιστής ","b":true,"c.....
07-20 05:33:26.545 13290 13325 W System.err: 	at kotlinx.serialization.json.internal.WriteModeKt.JsonDecodingException(SourceFile:1)
07-20 05:33:26.545 13290 13325 W System.err: 	at kotlinx.serialization.json.internal.WriteModeKt.JsonDecodingException(SourceFile:2)
07-20 05:33:26.545 13290 13325 W System.err: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(Unknown Source:58)
07-20 05:33:26.545 13290 13325 W System.err: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(Unknown Source:526)
07-20 05:33:26.545 13290 13325 W System.err: 	at com.mhss.app.mybrain.domain.model.SubTask$$serializer.deserialize(Unknown Source:20)
07-20 05:33:26.545 13290 13325 W System.err: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(Unknown Source:5)
07-20 05:33:26.545 13290 13325 W System.err: 	at kotlin.text.UStringsKt.decodeSerializableElement(Unknown Source:10)
07-20 05:33:26.545 13290 13325 W System.err: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(Unknown Source:49)
07-20 05:33:26.545 13290 13325 W System.err: 	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(Unknown Source:7)
07-20 05:33:26.545 13290 13325 W System.err: 	at kotlinx.serialization.internal.CollectionLikeSerializer.merge(Unknown Source:34)
07-20 05:33:26.545 13290 13325 W System.err: 	at kotlinx.serialization.internal.CollectionLikeSerializer.deserialize(Unknown Source:5)
07-20 05:33:26.545 13290 13325 W System.err: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(Unknown Source:5)
07-20 05:33:26.545 13290 13325 W System.err: 	at kotlinx.serialization.json.Json.decodeFromString(Unknown Source:30)
07-20 05:33:26.545 13290 13325 W System.err: 	at okio.Path$Companion.toSubTasksList(Unknown Source:21)
07-20 05:33:26.545 13290 13325 W System.err: 	at com.mhss.app.mybrain.data.local.dao.TaskDao_Impl$11.call(Unknown Source:531)
07-20 05:33:26.545 13290 13325 W System.err: 	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(Unknown Source:80)
07-20 05:33:26.545 13290 13325 W System.err: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
07-20 05:33:26.545 13290 13325 W System.err: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:112)
07-20 05:33:26.545 13290 13325 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-20 05:33:26.545 13290 13325 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-20 05:33:26.545 13290 13325 W System.err: 	at java.lang.Thread.run(Thread.java:764)
```

On both cases it seems to be about this, as you see:
```
07-20 05:33:26.545 13290 13325 W System.err: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 3: Encountered an unknown key 'a' at path: $[0]
07-20 05:33:26.545 13290 13325 W System.err: Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
07-20 05:33:26.545 13290 13325 W System.err: JSON input: [{"a":"🔋 φορτιστής ","b":true,"c.....
```

**Comment by mhss1** [comment]
@GiorgosXou That's weird, it looks like it's related to R8. Did you build the app by yourself or you have the one from F-Droid ?

**Comment by GiorgosXou** [comment]
The one from F-Droid.  I've no idea what R8 is 😅. My phone is way to old, might be even a sign of memory tearing\\failure *(because I remember exporting my data at some point, in the form of an sql database file [which, if I'm not being wrong is part of the latest version, right?])*

**Comment by GiorgosXou** [comment]
The only thing I care about are my notes, if I could somehow delete all tasks and still worked, I would be happy

**Comment by mhss1** [comment]
What is the exported file extension? If it is `sqlite3`, install the previous version of the app on another device (or on your current one if no data is on the app) and then import the data, and lastly update to the latest version and export the data in the new format If you want to import it in the future

**Comment by GiorgosXou** [comment]
@mhss1  it exports a `json` file of 0-bytes. As I said, it fails due to this error above

**Comment by mhss1** [comment]
I tried it on devices from Android 8 to 14 and it works without problems, so it might be because of your specifc device configurations. But I will look more into it.

**Comment by GiorgosXou** [comment]
It occured suddenly. I'm pretty sure that if I uninstall it and reinstall it *(lose all notes\\data)*, add some new notes and then export, it would work just fine, but...  I'm concerned it might happen again and I just don't want to lose my notes [...] Anyways thanks for looking into it and looking forward for any solution that might save my notes

**Comment by mhss1** [comment]
> did you try adding `🔋 φορτιστής` as a task? on an Android 8.1.0?
> 

Yes, on Android 8.0.0, but I'm pretty sure it is not the problem.

**Comment by GiorgosXou** [comment]
Did you find the issue?

**Comment by GiorgosXou** [comment]
I can't export my notes

**Comment by mhss1** [comment]
> Did you find the issue or a solution?
Yes, it should be fixed now

**Comment by GiorgosXou** [comment]
I can't find any release or recent commit... is it something related to the `dev`-branch? like, an upcoming update?

**Comment by mhss1** [comment]
It will be available in the next update

**Comment by GiorgosXou** [comment]
Just installed the latest version from f-droid and still I can't export:
```
--------- beginning of main
09-04 05:36:30.374  8888  8888 W zygote64: miui_dex2oat:　OatFile: /data/app/com.mhss.app.mybrain-Ofn1vKxj-V7Ef7YsEUJplw==/oat/arm64/base.odex Compiler-Filter = quicken
09-04 05:36:30.377  8888  8888 W ResourceType: No package identifier when getting name for resource number 0x00000000
09-04 05:36:30.424  8888  8888 I [Koin]  : Started 92 definitions in 8.653177 ms
09-04 05:36:30.437  8888  8888 D WM-PackageManagerHelper: Skipping component enablement for androidx.work.impl.background.systemjob.SystemJobService
09-04 05:36:30.438  8888  8888 D WM-Schedulers: Created SystemJobScheduler and enabled SystemJobService
09-04 05:36:30.447  8888  8888 W ResourceType: No package identifier when getting name for resource number 0x00000000
09-04 05:36:30.466  8888  8888 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
09-04 05:36:30.466  8888  8888 W ResourceType: No package identifier when getting name for resource number 0x00000000
09-04 05:36:30.496  8888  8888 D AccessibilityManager: AccessibilityManager status: mPackageName = com.mhss.app.mybrain, mOptimizeEnabled = false, mIsEnabled = false, mIsUiAutomationEnabled = false, mIsInterestedPackage =false
09-04 05:36:30.532  8888  8905 D OpenGLRenderer: HWUI GL Pipeline
09-04 05:36:30.692  8888  8893 I zygote64: Do partial code cache collection, code=22KB, data=27KB
09-04 05:36:30.692  8888  8893 I zygote64: After code cache collection, code=22KB, data=27KB
09-04 05:36:30.692  8888  8893 I zygote64: Increasing code cache capacity to 128KB
09-04 05:36:30.823  8888  8893 I zygote64: Do partial code cache collection, code=48KB, data=52KB
09-04 05:36:30.823  8888  8893 I zygote64: After code cache collection, code=48KB, data=52KB
09-04 05:36:30.823  8888  8893 I zygote64: Increasing code cache capacity to 256KB
09-04 05:36:30.825  8888  8893 I zygote64: Compiler allocated 5MB to compile void T.r.r(boolean)
09-04 05:36:30.859  8888  8888 I zygote64: Deoptimizing void T.r.r(boolean) due to JIT inline cache
09-04 05:36:31.084  8888  8893 I zygote64: Do full code cache collection, code=120KB, data=117KB
09-04 05:36:31.084  8888  8893 I zygote64: After code cache collection, code=56KB, data=36KB
09-04 05:36:31.215  8888  8893 I zygote64: Compiler allocated 5MB to compile void T.r.r(boolean)
09-04 05:36:31.238  8888  8888 I zygote64: Deoptimizing void T.r.r(boolean) due to JIT inline cache
09-04 05:36:31.423  8888  8893 I zygote64: Do partial code cache collection, code=118KB, data=105KB
09-04 05:36:31.423  8888  8893 I zygote64: After code cache collection, code=101KB, data=93KB
09-04 05:36:31.423  8888  8893 I zygote64: Increasing code cache capacity to 512KB
09-04 05:36:31.427  8888  8893 I zygote64: Compiler allocated 5MB to compile void T.r.r(boolean)
09-04 05:36:31.469  8888  8905 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/04/18, d916c72, I7663a5f222
09-04 05:36:31.474  8888  8905 D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
09-04 05:36:31.482  8888  8905 I zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
09-04 05:36:31.482  8888  8905 I OpenGLRenderer: Initialized EGL, version 1.4
09-04 05:36:31.482  8888  8905 D OpenGLRenderer: Swap behavior 2
09-04 05:36:31.490  8888  8905 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
09-04 05:36:31.492  8888  8905 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
09-04 05:36:31.494  8888  8905 D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
09-04 05:36:31.586  8888  8888 I zygote64: Deoptimizing int r.v.d(java.lang.Object) due to JIT inline cache
09-04 05:36:31.588  8888  8888 I zygote64: Deoptimizing void d0.A.<init>() due to JIT inline cache
09-04 05:36:31.631  8888  8888 I Choreographer: Skipped 63 frames!  The application may be doing too much work on its main thread.
--------- beginning of system
09-04 05:36:31.632  8888  8888 W Looper  : Slow Frame: doFrame is 1051ms late
09-04 05:36:31.703  8888  8888 I zygote64: Deoptimizing void w2.w.<init>(w2.N, b6.b, java.util.Map) due to JIT inline cache
09-04 05:36:31.748  8888  8888 I zygote64: Deoptimizing java.lang.Object C0.Y.d() due to JIT inline cache
09-04 05:36:31.914  8888  8905 D vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
09-04 05:36:31.915  8888  8905 D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
09-04 05:36:31.943  8888  8893 I zygote64: Do full code cache collection, code=251KB, data=193KB
09-04 05:36:31.943  8888  8893 I zygote64: After code cache collection, code=194KB, data=105KB
09-04 05:36:31.993  8888  8888 W Looper  : Slow Frame: doFrame is 345ms late
09-04 05:36:38.249  8888  8888 I zygote64: Deoptimizing l6.j l6.j.f() due to JIT inline cache
09-04 05:36:38.351  8888  8888 I zygote64: Deoptimizing d0.A d0.m.t(d0.A, d0.y) due to JIT inline cache
09-04 05:36:38.353  8888  8888 I zygote64: Deoptimizing void T.r.Q(java.lang.Object, int, java.lang.Object, int) due to JIT inline cache
09-04 05:36:38.385  8888  8893 I zygote64: Do partial code cache collection, code=245KB, data=176KB
09-04 05:36:38.386  8888  8893 I zygote64: After code cache collection, code=217KB, data=165KB
09-04 05:36:38.386  8888  8893 I zygote64: Increasing code cache capacity to 1024KB
09-04 05:36:38.892  8888  8888 I zygote64: Deoptimizing java.lang.Object K5.c.X(java.lang.Object, U5.e) due to JIT inline cache
09-04 05:36:38.920  8888  8888 W Looper  : Slow Frame: doFrame is 488ms late
09-04 05:36:39.001  8888  8893 I zygote64: Compiler allocated 4MB to compile java.lang.Object k4.i0.h(java.lang.Object, java.lang.Object, java.lang.Object)
09-04 05:36:39.255  8888  8888 I zygote64: Deoptimizing int T.r.k(int, int, int, int) due to JIT inline cache
09-04 05:36:39.441  8888  8893 I zygote64: Do full code cache collection, code=499KB, data=410KB
09-04 05:36:39.442  8888  8893 I zygote64: After code cache collection, code=460KB, data=269KB
09-04 05:36:42.281  8888  8893 I zygote64: Do partial code cache collection, code=504KB, data=344KB
09-04 05:36:42.282  8888  8893 I zygote64: After code cache collection, code=504KB, data=344KB
09-04 05:36:42.282  8888  8893 I zygote64: Increasing code cache capacity to 2MB
09-04 05:36:42.347  8888  8888 I zygote64: Deoptimizing java.lang.Object A.h0.j(java.lang.Object, java.lang.Object) due to JIT inline cache
09-04 05:36:42.387  8888  8893 I zygote64: Compiler allocated 6MB to compile void l5.f.g(w2.B, w2.y, f0.q, f0.d, U5.c, U5.c, U5.c, U5.c, U5.c, T.r, int)
09-04 05:36:42.456  8888  8888 I zygote64: Deoptimizing void f6.N.run() due to JIT inline cache
09-04 05:36:42.459  8888  8888 I zygote64: Deoptimizing l6.j l6.j.f() due to JIT inline cache
09-04 05:36:44.152  8888  8888 I zygote64: Deoptimizing K5.d N6.d.J(K5.d) due to JIT inline cache
09-04 05:36:44.269  8888  8893 I zygote64: Compiler allocated 5MB to compile java.lang.Object Q.a.d()
09-04 05:36:44.291  8888  8888 I zygote64: Deoptimizing boolean f6.p0.G(java.lang.Object) due to JIT inline cache
09-04 05:36:44.292  8888  8888 I zygote64: Deoptimizing boolean f6.p0.I(java.lang.Throwable) due to JIT inline cache
09-04 05:36:44.292  8888  8888 I zygote64: Deoptimizing void f6.a.o0(java.lang.Object) due to JIT same target
09-04 05:36:44.452  8888  8905 W Adreno-ES20: <core_glFinish:34>: glFinish skipped: 0
09-04 05:36:44.467  8888  8905 W Adreno-ES20: <core_glFinish:34>: glFinish skipped: 0
09-04 05:36:44.499  8888  8905 W Adreno-ES20: <core_glFinish:34>: glFinish skipped: 0
09-04 05:36:44.502  8888  8888 I zygote64: Deoptimizing void f6.l.p(int) due to JIT inline cache
09-04 05:36:44.503  8888  8906 I zygote64: Deoptimizing java.lang.Object K5.c.X(java.lang.Object, U5.e) due to JIT inline cache
09-04 05:36:44.503  8888  8906 I zygote64: Deoptimizing java.lang.Object l6.b.n(K5.i, java.lang.Object) due to JIT inline cache
09-04 05:36:44.504  8888  8906 I zygote64: Deoptimizing java.lang.Object l6.b.m(K5.i) due to JIT inline cache
09-04 05:36:44.509  8888  8905 W Adreno-ES20: <core_glFinish:34>: glFinish skipped: 0
09-04 05:36:47.071  8888  8905 W Adreno-ES20: <core_glFinish:34>: glFinish skipped: 0
09-04 05:36:47.071  8888  8905 W Adreno-ES20: <core_glFinish:34>: glFinish skipped: 0
09-04 05:36:47.081  8888  8888 I zygote64: Deoptimizing java.lang.Object K5.b.j(java.lang.Object, java.lang.Object) due to JIT inline cache
09-04 05:36:47.100  8888  8888 I zygote64: Deoptimizing void f6.N.run() due to JIT inline cache
09-04 05:36:47.131  8888  8905 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
09-04 05:36:47.140  8888  8905 D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
09-04 05:36:47.177  8888  8947 I zygote64: Deoptimizing void f6.p0.P(f6.e0, java.lang.Object) due to JIT inline cache
09-04 05:36:47.180  8888  8906 I zygote64: Deoptimizing void l6.b.j(K5.d, java.lang.Object, U5.c) due to JIT inline cache
09-04 05:36:47.266  8888  8923 W System.err: D6.q: Unexpected JSON token at offset 3: Encountered an unknown key 'a' at path: $[0]
09-04 05:36:47.266  8888  8923 W System.err: Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
09-04 05:36:47.266  8888  8923 W System.err: JSON input: [{"a":"🔋 φορτιστής ","b":true,"c.....
09-04 05:36:47.266  8888  8923 W System.err: 	at D6.v.d(Unknown Source:36)
09-04 05:36:47.266  8888  8923 W System.err: 	at D6.v.e(Unknown Source:34)
09-04 05:36:47.266  8888  8923 W System.err: 	at D6.a.q(Unknown Source:58)
09-04 05:36:47.266  8888  8923 W System.err: 	at D6.I.p(Unknown Source:373)
09-04 05:36:47.266  8888  8923 W System.err: 	at d4.u.b(Unknown Source:21)
09-04 05:36:47.266  8888  8923 W System.err: 	at D6.I.b(Unknown Source:281)
09-04 05:36:47.266  8888  8923 W System.err: 	at H7.e.D(Unknown Source:10)
09-04 05:36:47.266  8888  8923 W System.err: 	at D6.I.D(Unknown Source:49)
09-04 05:36:47.266  8888  8923 W System.err: 	at B6.s.j(Unknown Source:7)
09-04 05:36:47.266  8888  8923 W System.err: 	at B6.a.i(Unknown Source:34)
09-04 05:36:47.266  8888  8923 W System.err: 	at B6.a.b(Unknown Source:5)
09-04 05:36:47.266  8888  8923 W System.err: 	at D6.I.b(Unknown Source:281)
09-04 05:36:47.266  8888  8923 W System.err: 	at C6.c.a(Unknown Source:29)
09-04 05:36:47.266  8888  8923 W System.err: 	at V0.h.s(Unknown Source:22)
09-04 05:36:47.266  8888  8923 W System.err: 	at Y3.q.call(Unknown Source:531)
09-04 05:36:47.266  8888  8923 W System.err: 	at C2.b.r(Unknown Source:80)
09-04 05:36:47.266  8888  8923 W System.err: 	at M5.a.v(Unknown Source:8)
09-04 05:36:47.266  8888  8923 W System.err: 	at f6.N.run(Unknown Source:112)
09-04 05:36:47.266  8888  8923 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
09-04 05:36:47.266  8888  8923 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
09-04 05:36:47.266  8888  8923 W System.err: 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by mhss1** [comment]
@GiorgosXou Are you sure you are exporting and not importing?

**Comment by GiorgosXou** [comment]
Yes 
![Screenshot_2024-09-04-15-23-33-188_com mhss app mybrain_1](https://github.com/user-attachments/assets/9a11cf4d-b9e6-44ec-a475-c793368c2437)

**Comment by mhss1** [comment]
@GiorgosXou can you follow these steps:
1. download app1.apk from the link below and install it on your device (you can install it beside the current app)
2. add some tasks and notes and try to export. (it should fail as the current app)
3. download app2.apk and install it to update the previous one and try to export. (it should export successfully)

download link: https://quickshare.samsungcloud.com/wjWa7sJDagQD

**Comment by GiorgosXou** [comment]
Both "app1.apk" and "app2.apk" export successfully to a json file *(including when I add tasks)*. 

I suspect that the issue isn't so related to the exporting mechanism, due to the fact that it fails to open tasks anyways. I think it's either due to a memory-failure during write *(my phone is too old)* or something else. Either way I don't care about tasks so if by ignoring them or erasing them somehow I could export my notes I'd be happy too

**Comment by mhss1** [comment]
You can manually move the data to this and export it. 
And then, clear the app data (the main one), uninstall it, reinstall the app from f-droid and import the data.

**Comment by GiorgosXou** [comment]
Wdym manually? I have about a thousand notes... Is there a way of overwriting tasks by importing a json file *(consisting of only tasks)*, without effecting notes?

**Comment by mhss1** [comment]
Oh, then I will add an option to choose what types to export in the next release so you can export all data except tasks.

**Comment by mhss1** [comment]
The issue is finally fixed now.
