### ISSUE TITLE
App crashes on opening Tasks and Dashboard

### ISSUE THREAD

**Issue by 21jujubees** [mhss1/MyBrain#223]
**Describe the bug***
For me, MyBrain boots to Spaces, but when I try to open Tasks, it gives me this error:

`
D6.q: Unexpected JSON token at offset 3: Encountered an unknown key 'a' at path: $[0]
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
JSON input: [{"a":"Make it look good lmao","b":false,"c":"20e7c1c1-1af2-4429-85b2-55264097bb37"},{"a":"Add next/prev buttons","b":false,"c":"3de57f7b-ab27-4694-89d1-4026e3b67c55"}]
	at D6.v.d(Unknown Source:36)
	at D6.v.e(Unknown Source:34)
	at D6.a.q(Unknown Source:58)
	at D6.I.p(Unknown Source:373)
	at d4.u.b(Unknown Source:21)
	at D6.I.b(Unknown Source:281)
	at H7.e.D(Unknown Source:10)
	at D6.I.D(Unknown Source:49)
	at B6.s.j(Unknown Source:7)
	at B6.a.i(Unknown Source:34)
	at B6.a.b(Unknown Source:5)
	at D6.I.b(Unknown Source:281)
	at C6.c.a(Unknown Source:29)
	at V0.h.s(Unknown Source:22)
	at Y3.q.call(Unknown Source:531)
	at C2.b.r(Unknown Source:80)
	at M5.a.v(Unknown Source:8)
	at f6.N.run(Unknown Source:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: l6.f: [w0{Cancelling}@853ed2d, Dispatchers.Main.immediate]
`

When I try to go to the Dashboard, I get this error:

`
D6.q: Unexpected JSON token at offset 3: Encountered an unknown key 'a' at path: $[0]
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
JSON input: [{"a":"Make it look good lmao","b":false,"c":"20e7c1c1-1af2-4429-85b2-55264097bb37"},{"a":"Add next/prev buttons","b":false,"c":"3de57f7b-ab27-4694-89d1-4026e3b67c55"}]
	at D6.v.d(Unknown Source:36)
	at D6.v.e(Unknown Source:34)
	at D6.a.q(Unknown Source:58)
	at D6.I.p(Unknown Source:373)
	at d4.u.b(Unknown Source:21)
	at D6.I.b(Unknown Source:281)
	at H7.e.D(Unknown Source:10)
	at D6.I.D(Unknown Source:49)
	at B6.s.j(Unknown Source:7)
	at B6.a.i(Unknown Source:34)
	at B6.a.b(Unknown Source:5)
	at D6.I.b(Unknown Source:281)
	at C6.c.a(Unknown Source:29)
	at V0.h.s(Unknown Source:22)
	at Y3.q.call(Unknown Source:531)
	at C2.b.r(Unknown Source:80)
	at M5.a.v(Unknown Source:8)
	at f6.N.run(Unknown Source:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: l6.f: [w0{Cancelling}@cfc7541, Dispatchers.Main.immediate]
`

**To Reproduce**
1. Open the app.
2. Click on 'Tasks'/'Dashboard'
3. See error

**Smartphone (please complete the following information):**
 - Device: Google Pixel 8a
 - OS: Android 14
 - App Version: 2.0

**Additional context**
When I try to export my data, it says that "Something went wrong when exporting," and exports a 0B json file. This is also an app I've been using for a couple of years with a lot of notes and diary entries.

**Comment by mhss1** [comment]
Hi, sorry for this problem.
It has been fixed and I will push the update very soon.
