### ISSUE TITLE
Clicking event on dashboard crashes

### ISSUE THREAD

**Issue by MysterJacob** [mhss1/MyBrain#248]
Pressing an event on calendar crashes the app.

**To Reproduce**
1. Go to 'Dashboard'
2. Click on any event

 - Device: Oppo Reno 8T
 - OS: ColorOS 14.0
 - App Version 2.0.0
 
Error log:
```
java.lang.IllegalArgumentException: Invalid symbol '{'(173) at index 0
	at l2.I.c(Unknown Source:521)
	at k4.U.g(Unknown Source:112)
	at b0.a.e(Unknown Source:43)
	at b0.a.g(Unknown Source:8)
	at A.w.j(Unknown Source:76)
	at b0.a.j(Unknown Source:51)
	at T.e.a(Unknown Source:232)
	at c0.g.e(Unknown Source:148)
	at l5.d.l(Unknown Source:195)
	at A.w.j(Unknown Source:114)
	at b0.a.j(Unknown Source:51)
	at T.e.b(Unknown Source:149)
	at l5.d.e(Unknown Source:109)
	at s4.x2.g(Unknown Source:94)
	at b0.a.e(Unknown Source:43)
	at b0.a.g(Unknown Source:8)
	at I.t0.h(Unknown Source:151)
	at b0.a.b(Unknown Source:43)
	at b0.a.h(Unknown Source:8)
	at androidx.compose.animation.a.a(Unknown Source:1427)
	at N.r0.j(Unknown Source:287)
	at b0.a.j(Unknown Source:51)
	at l5.f.b(Unknown Source:938)
	at l5.f.g(Unknown Source:2255)
	at x2.x.j(Unknown Source:243)
	at T.r.G(Unknown Source:437)
	at T.r.N(Unknown Source:136)
	at T.r.p(Unknown Source:243)
	at T.r.E(Unknown Source:31)
	at T.v.w(Unknown Source:21)
	at T.v0.q(Unknown Source:106)
	at R.f1.o(Unknown Source:614)
	at F0.e0.doFrame(Unknown Source:33)
	at F0.c0.doFrame(Unknown Source:47)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1542)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1553)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1109)
	at android.view.Choreographer.doFrame(Choreographer.java:984)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1527)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
	Suppressed: l6.f: [F0.f0@92b1018, F0.J0@cd5a71, w0{Cancelling}@d642056, d0@e0028d7]

```

**Comment by mhss1** [comment]
This issue is already fixed. Please update the app to the latest version.
